---

- name: check if .git exists in /etc
  stat:
    path: /etc/.git
  register: git_exists
  check_mode: no

- name: git reset
  command: git reset
  args:
    chdir: /etc
  register: git_reset
  changed_when: git_reset.stdout
  when: git_exists.stat.exists

- name: check status of common account files
  command: git status --porcelain -- php5/cli/php.ini php5/fpm/php.ini
  args:
    chdir: /etc
  register: git_status
  check_mode: no
  changed_when: git_status.stdout
  when: git_exists.stat.exists

- name: git add changed files
  command: git add --all -- php5/cli/php.ini php5/fpm/php.ini
  args:
    chdir: /etc
  when:
  - "'skipped' not in git_status"
  - git_status.stdout

- name: git commit changes
  command: git commit -m "autocommit after ansible-role-pecl-mongodriver"
  args:
    chdir: /etc
  ignore_errors: True
  when:
  - "'skipped' not in git_status"
  - git_status.stdout

...
