---

# FIXME use pear module

# Adding Sury repo
- block:
  - name: Add packages.sury.org repository key
    apt_key:
      id: "15058500A0235D97F5D10063B188E2B695BD4743"
      keyring: /etc/apt/trusted.gpg.d/php5.gpg
      url: "{{ php5_apt_key_url }}"
      state: present

  - name: Add php5 repository
    apt_repository:
      repo: "deb {{ php5_repo_url }} {{ ansible_distribution_release }} main"
      filename: "php5"

  when: (ansible_distribution_release == "jessie") or
        (ansible_distribution_release == "wheezy") or
        (ansible_distribution_release == "stretch" and php5_version != '7.0')
# end block

- name: install SSL libraries
  apt:
    name: "{{ item }}"
    state: present
    purge: false
    install_recommends: false
    autoremove: false
    allow_unauthenticated: false
    dpkg_options: 'force-confdef,force-confold'
  with_items:
  - libssl-dev
  - libssl1.1
  - pkg-config
  - php5.6-fpm
  - php5.6-cli
  - php5.6-dev
  - php5.6-xml
  - php-pear

- name: set php.ini for PECL
  shell: pecl config-set php_ini /etc/php.ini

- name: discover default extensions directory
  shell: php -i | grep -i '^extension_dir' | awk '{print $3}'
  register: php_extension_dir

- name: uninstall old MONGO drivers before continuing
  shell: pecl uninstall mongo
  ignore_errors: yes

- name: install Mongo Driver
  shell: printf "\n" | pecl install mongo
  args:
    creates: "{{php_extension_dir.stdout_lines[0]}}/mongo.so"

- name: set Mongo Driver as executable
  file:
    path: "{{php_extension_dir.stdout_lines[0]}}/mongo.so"
    mode: "0755"

- name: add Mongo extension to PHP (HTTP)
  lineinfile:
    dest: /etc/php/5.6/fpm/php.ini
    line: "extension={{php_extension_dir.stdout_lines[0]}}/mongo.so"
    state: present

- name: add Mongo extension to PHP (CLI)
  lineinfile:
    dest: /etc/php/5.6/cli/php.ini
    line: "extension={{php_extension_dir.stdout_lines[0]}}/mongo.so"
    state: present

- name: commit to /etc repo
  include: etckeeper.yaml
  tags:
  - pecl-mongodriver-etckeeper

...
